### ISSUE TITLE
Saved Templates Are Not Showing

### ISSUE THREAD

**Issue by eece** [infazz/flexible-templates#1]
Hi I saved a template from flexible content in page edit but, I can't see this template.
![image](https://user-images.githubusercontent.com/18285160/27432267-2aadcc40-5758-11e7-8fd6-12c4c7f8641f.png)

**Comment by infazz** [comment]
Hi, the template list should be there, as you see on the screen:
![screen shot 2017-06-22 at 14 52 27](https://user-images.githubusercontent.com/2073096/27432864-b7821dfe-575a-11e7-89d5-c848f7a2a7d5.png)

What version of ACF you are using?

**Comment by eece** [comment]
I'm using Version: 5.3.0

**Comment by infazz** [comment]
Much I see, the hook used there should work in your version. is it possible to have access to the server to try to debug the issue?

**Comment by eece** [comment]
It is my on localhost. I think 

add_filter("acf/get_field_label", array($this, 'filter_get_field_label'), 10, 2);

 is not working. Are you sure get_field_label is true hook?

**Comment by infazz** [comment]
I'm sure, as its working for me on multiple different install's

Heres screen from ACF code, hook there since v5.0.0:
<img width="668" alt="screen shot 2017-06-22 at 15 35 51" src="https://user-images.githubusercontent.com/2073096/27434202-8badd97e-5760-11e7-9228-c433d4a430a0.png">

**Comment by infazz** [comment]
Can you enable debug, and see maybe for some errors?

**Comment by eece** [comment]
I opened debug from wp-config there is no any error. I checked console in my browser, no error.

**Comment by eece** [comment]
Saving template function is working. It is checking is there existing template with same name.

**Comment by infazz** [comment]
@eece try updated version of plugin and report please

**Comment by eece** [comment]
Hi thanks for update. I updated plugin but now, It is not saving template. Previous version was doing it well. Templates button still not showing. 
![image](https://user-images.githubusercontent.com/18285160/27498281-03e9340e-5867-11e7-952c-7e20274b0a15.png)

**Comment by infazz** [comment]
@eece Unfortunetly I can't confirm any of the issue you experience on my instances. I checked the on 4 different server setup's and all working fine. All saving well after update and also templates showing up. None of the saving functionality was touched by the way, in the last update and committed only updated file.
There something with your setup I guess. Would be very helpful and I will be glad to help if you upload site somewhere online and we could debug the issue together.

**Comment by eece** [comment]
I cant move it live because of my project progression. But when it's finished I'll send it to you.
