### ISSUE TITLE
Cant load saved template?

### ISSUE THREAD

**Issue by pierrerocket** [infazz/flexible-templates#2]
Hello,

Im testing out this plugin (which would be a total game change for us if it worked), and while it seems like I can save a template just fine, when I go to load a template on a page the flex content area stays empty/no blocks are added.

I am running the latest version of WP and ACF Pro (5.6.1)

I checked the database to make sure things are saving. It seems like it is saving SOMETHING... here is what it looks like:

SELECT * FROM `wp_flexible_templates_acf`

```
ID: 
3
name: 
Test 2
template: 
%3Cdiv%20class%3D%22values%22%3E%0A%09%09%09%3Cul%20class%3D%22acf-bl%20list%22%3E%0A%09%09%09%09%09%09%3C/ul%3E%0A%09%09%3C/div%3E
```

Which decodes to:
```
<div class="values">
			<ul class="acf-bl list">
						</ul>
		</div>


```
Which sure doesnt seem like what should be stored in that table.  Help?

**Comment by infazz** [comment]
Hi, thanks for testing it! It stores the right data, if you read readme, youll see it also say, that html data is saved, this is because of tinymce editors in repeater fields can occur there. So the html of generated flexible fields is saved and than loaded back. 

What I can think of for now, can you try to save page first, where you want to load the saved template, and try to load it than. 

Please let me know of the result!

Also if you have it somewhere online, I would be happy to see what causes the issue there.

**Comment by pierrerocket** [comment]
Hello @infazz 

I just tested that, with no success.  I have tried saving the page, then adding my blocks, then saving the template. Creating a new page, then saving the page, then loading the saved template.  

I would be happy to deploy this site from my local dev to a server if you would be willing to take a look at things.

**Comment by infazz** [comment]
@pierrerocket 
Yes please, deploy it somewhere, so I could check. Also just installed it on fresh site to test, and seem to work nicely for me.

Lets try to debug what causing the issue for you.

**Comment by infazz** [comment]
@pierrerocket also, what OS and browser you used?

**Comment by pierrerocket** [comment]
@infazz I'm on Mac OSX Sierra 10.12.5, chrome Version 59.0.3071.115 (Official Build) (64-bit).

I just loaded up firefox to make sure that isnt the issue.

SIte is a clean wordpress install, the theme is my own and based on _s (underscores).  There are no js errors in console.  I will deploy the site to my personal server in the morning and get back to you.  THanks for the help!

**Comment by pierrerocket** [comment]
@infazz I have the site deployed to a temporary location that is publicly accessible.  Please email me pierre@XXXXXXXX.XXX and I will get you creds.

Thanks!
