### ISSUE TITLE
Editing in both WYSIWYG and raw editor.

### ISSUE THREAD

**Issue by swmcgithub** [infazz/flexible-templates#3]
Let me start by saying this plugin is amazing.

I found a weird behavior when editing in both the WYSIWYG editor and the raw HTML code editor of a WYSIWYG field.

If i edit in the WYSIWYG editor, then switch to the HTML editor, I cannot update the code—it overrides with what was there before I switched views about every second or so.

I have attached a quick screen recording (mp4) demoing this behavior.

Any feedback / help would be greatly appreciated.
[sampleerror.mp4.zip](https://github.com/infazz/flexible-templates/files/1242984/sampleerror.mp4.zip)

**Comment by infazz** [comment]
Спасибо!
Spark by Readdle

**Comment by infazz** [comment]
@swmcgithub hey, sorry for late respose, but I guess this issue is fixed in lates version, please have a try
