### ISSUE TITLE
Different templates for different flexible content fields

### ISSUE THREAD

**Issue by virgo79** [infazz/flexible-templates#4]
Hi,

thanks for developed this plugin. It's really awesome and a great starting point.

I've created 2 flexible content fields, one for posts and another for pages and both have different row layouts.
The problem is that both loads the same templates. so if I save a template created with fc in posts it can be loaded in the fc of pages, but this is not correct for the fc in pages. the result is that, after page reload the fc result empty.

Is there a way to create templates related to a specific flexible content field?

Thanks in advance.

**Comment by infazz** [comment]
@virgo79 sorry for late respose, but I guess this issue is fixed in lates version, please have a try :)
