### ISSUE TITLE
Can't save templates within nested Flex field

### ISSUE THREAD

**Issue by tmconnect** [infazz/flexible-templates#5]
I have a Flex field within a Flex field. After entering a template name and clicking "Save this template" I got the error "Please input template name." and the template is not saved.

I tried this also with a Flex field within a Repeater field. Here I can't save any template, too - but there's no error message.

Any ideas what's gong wrong.

**Comment by infazz** [comment]
@tmconnect Hi , sorry for tooo late responce :) 
Unfortunetly, saving nested flexible content is quite hardly achivable. 
but you still can save top level flexible content with new update, it also now separates templates by post tag
